name: Cypress Tests

 

on:
  push:
    branches:
      - main

 

jobs:
  cypress-tests:
    runs-on: ubuntu-latest

 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

 

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

 

      - name: Install dependencies
        run: npm ci

 

      - name: Run Cypress tests
        id: cypress
        run: npm cypress run

 

      - name: Check test results
        run: |
          if [ ${{ steps.cypress.outcome }} == 'success' ]; then
            echo "All tests passed"
            # Push the code
            git push origin main
          else
            echo "Tests failed"
            # Revert the code to the previous commit
            git reset --hard HEAD^
            # Force push the reverted code
            git push --force origin main
          