name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Run Cypress tests
        uses: cypress-io/github-action@v2
        with:
            build: npm run build
            start: npm run dev
            wait-on: 'http://localhost:3000'
            command: npx cypress run --reporter json --reporter-options output=results.json
      - name: Check test results and revert changes if needed
        run: |
                if [[ $(jq -r '.stats.failures' results.json) != "0" ]]; then
                git reset --hard HEAD~1
                git push -f
                fi
            # Ensure this step runs only if previous steps were successful
        if: ${{ success() }}
